name: Upload Server

on: [push]

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    # Aqui você deve adicionar os comandos para buildar seu servidor
    
    - name: Upload Server
      uses: actions/upload-artifact@v2
      with:
        name: server
        path: /home/alfredo/Documentos/Controle-De-Datas-
